apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hawtio-dev

resources:
- ../crs/hawtio_v2_hawtio_cr.yaml
images:
- name: quay.io/hawtio/operator
  newName: quay.io/hawtio/operator
  newTag: 1.3.0
