apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../deploy/crd
- ../deploy/crs
- ../deploy
- scorecard
images:
- name: quay.io/hawtio/operator
  newName: quay.io/phantomjinx/hawtio-operator
  newTag: 1.3.0-7-202511101115
